version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default

linters:
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert
  disable:
    - errcheck      # Too many false positives, enable later
    - unused        # Helper functions for future use
    - staticcheck   # Suggestions, not errors
    - gosec         # Security checks, enable later with proper config

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - encoding/json.(*Encoder).Encode
      - (*encoding/json.Encoder).Encode
      - io.Copy
      - (io.Closer).Close
  gosec:
    excludes:
      - G101
      - G104
      - G203
      - G401
      - G404
      - G501
      - G304
      - G107
      - G204

issues:
  exclude-use-default: true
  max-issues-per-linter: 100
  max-same-issues: 10
  exclude-files:
    - "cmd/test_calendar/.*"
  exclude-dirs:
    - scripts
    - internal/initializer/app
  exclude-rules:
    - text: "G104"
      linters:
        - gosec
