version: '3'

vars:
  GO_VERSION: '1.24'
  GOLANGCI_LINT_VERSION: 'v2.1.5'
  GCI_VERSION: 'v0.13.6'
  GOFUMPT_VERSION: 'v0.8.0'
  
  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'

tasks:
  install-formatters:
    desc: "Устанавливает форматтеры gci и gofumpt в ./bin"
    summary: |
      Эта задача проверяет наличие инструментов форматирования кода gofumpt и gci в директории bin.
      Если инструменты не найдены, они будут автоматически установлены с указанными версиями.
      
      Используется:
        - gofumpt: для форматирования кода Go
        - gci: для сортировки импортов Go
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          echo '📦 Устанавливаем gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          echo '📦 Устанавливаем gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  format:
    desc: "Форматирует весь проект gofumpt + gci"
    deps: [install-formatters]
    cmds:
      - |
        echo "🧼 Форматируем через gofumpt..."
        find . -type f -name '*.go' ! -path '*/vendor/*' ! -path '*/bin/*' -exec {{.GOFUMPT}} -extra -w {} +
      - |
        echo "🎯 Сортируем импорты через gci..."
        find . -type f -name '*.go' ! -path '*/vendor/*' ! -path '*/bin/*' -exec {{.GCI}} write -s standard -s default {} +
      - echo "✅ Форматирование завершено"

  install-golangci-lint:
    desc: "Устанавливает golangci-lint в каталог bin"
    summary: |
      Проверяет наличие golangci-lint в директории bin.
      Если инструмент не найден, автоматически устанавливает его через go install.
      
      Устанавливаемая версия: {{.GOLANGCI_LINT_VERSION}}
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Устанавливаем golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}

  lint:
    desc: "Запускает golangci-lint для проекта"
    deps: [install-golangci-lint]
    cmds:
      - |
        echo "🔍 Запускаем golangci-lint..."
        {{.GOLANGCI_LINT}} run ./... --config=.golangci.yml

  test:
    desc: "Запускает все тесты проекта"
    cmds:
      - |
        echo "🧪 Запускаем тесты..."
        go test -v -race -cover ./...

  test:coverage:
    desc: "Запускает тесты с детальным покрытием"
    cmds:
      - |
        echo "🧪 Запускаем тесты с покрытием..."
        go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        go tool cover -html=coverage.out -o coverage.html
        echo "📊 Отчет сохранен в coverage.html"

  run:parser:
    desc: "Запускает parser процесс"
    cmds:
      - |
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        echo "🚀 Запускаем parser..."
        go run ./cmd/parser

  run:bot:
    desc: "Запускает bot процесс"
    cmds:
      - |
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        echo "🤖 Запускаем bot..."
        go run ./cmd/bot

  run:stats:
    desc: "Запускает stats_parser процесс"
    cmds:
      - |
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        echo "📊 Запускаем stats parser..."
        go run ./cmd/stats_parser

  run:fhspb:
    desc: "Запускает fhspb_parser процесс"
    cmds:
      - |
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        echo "🏒 Запускаем fhspb parser..."
        go run ./cmd/fhspb_parser

  build:parser:
    desc: "Собирает бинарник parser"
    cmds:
      - |
        echo "🔨 Собираем parser..."
        mkdir -p {{.BIN_DIR}}
        go build -o {{.BIN_DIR}}/parser ./cmd/parser

  build:bot:
    desc: "Собирает бинарник bot"
    cmds:
      - |
        echo "🔨 Собираем bot..."
        mkdir -p {{.BIN_DIR}}
        go build -o {{.BIN_DIR}}/bot ./cmd/bot

  build:stats:
    desc: "Собирает бинарник stats_parser"
    cmds:
      - |
        echo "🔨 Собираем stats_parser..."
        mkdir -p {{.BIN_DIR}}
        go build -o {{.BIN_DIR}}/stats_parser ./cmd/stats_parser

  build:fhspb:
    desc: "Собирает бинарник fhspb_parser"
    cmds:
      - |
        echo "🔨 Собираем fhspb_parser..."
        mkdir -p {{.BIN_DIR}}
        go build -o {{.BIN_DIR}}/fhspb_parser ./cmd/fhspb_parser

  build:all:
    desc: "Собирает все бинарники"
    deps: [build:parser, build:bot, build:stats, build:fhspb]
    cmds:
      - echo "✅ Все бинарники собраны"

  clean:
    desc: "Очищает generated файлы и бинарники"
    cmds:
      - |
        echo "🧹 Очистка..."
        rm -rf {{.BIN_DIR}}
        rm -f coverage.out coverage.html
        echo "✅ Очистка завершена"

  db:clear:
    desc: "Очищает все таблицы в БД"
    cmds:
      - |
        echo "🗑️  Очистка БД..."
        go run ./scripts/db_clear.go

  db:stats:
    desc: "Показывает быструю статистику БД"
    cmds:
      - go run ./scripts/db_stats.go

  db:report:
    desc: "Генерирует полный отчет по данным в БД"
    cmds:
      - go run ./scripts/db_report.go

  db:verify-stats:
    desc: "Проверяет покрытие статистики игроков"
    cmds:
      - |
        echo "🔍 Проверка покрытия статистики игроков..."
        go run ./scripts/verify_player_stats.go

  db:verify-tournaments:
    desc: "Проверяет покрытие статистики по турнирам"
    cmds:
      - |
        echo "🔍 Проверка покрытия по турнирам..."
        go run ./scripts/verify_tournament_stats.go

  db:migrate:
    desc: "Запускает миграции БД"
    cmds:
      - |
        echo "🔄 Запускаем миграции..."
        go run ./cmd/migrate
        echo "✅ Миграции применены"

  parser:full:
    desc: "Полный цикл парсинга (очистка БД + миграции + парсинг всех доменов)"
    cmds:
      - |
        echo "🔧 Компиляция парсера..."
        task build:parser
        echo ""
        echo "🗑️  Очистка БД..."
        go run ./scripts/db_clear.go
        echo ""
        echo "🔄 Применение миграций..."
        task db:migrate
        echo ""
        echo "🚀 Запускаю парсер всех 23 доменов..."
        echo ""
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        ./bin/parser
        echo ""
        echo "✅ Парсинг завершен! Проверь результаты: task db:stats"

  stats:full:
    desc: "Полный цикл парсинга статистики турниров"
    cmds:
      - |
        echo "🔧 Компиляция stats_parser..."
        task build:stats
        echo ""
        echo "📊 Запускаю парсинг статистики всех турниров..."
        if [ -f .env ]; then
          export $(cat .env | grep -v '^#' | xargs)
        fi
        ./bin/stats_parser
        echo ""
        echo "✅ Парсинг статистики завершен!"
        echo "📊 Проверь результаты:"
        echo "   task db:stats              # Общая статистика"
        echo "   task db:verify-stats       # Покрытие игроков"
        echo "   task db:verify-tournaments # Покрытие турниров"

  help:
    desc: "Показывает список всех доступных задач"
    cmds:
      - task --list
